### ISSUE TITLE
@channels are not being cleared out from EXERCISES_OF_THE_DAY

### ISSUE THREAD

**Issue by pyasi** [hudl/slackbot-workout#42]
When the bot does the group callout, the EOD reminder will remind everybody in the channel of the missed exercise. However, the next day, anyone who still hasn't acknowledged the group callout exercise will be reminded again. This leads to a massive spam of people who haven't done the exercise

**Comment by MatthewBrand** [comment]
I just added this line after we reset the exercises:
`print "number of exercises for day " + str(len(EXERCISES_FOR_DAY))`

and I got an output of 

> number of exercises for day 1

So, the reset is getting called, it's just not working.
